apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels: 
    component: web
spec:
  containers:
    - name: client
      image: c1495616/k8s-express-demo
      ports: 
        - containerPort: 3000